baseUrl: https://shop-api.e-ncp.com
countryCode: KR
siteId: 2
siteName: KASINA
siteProfiles:
- crawlAuthSetting:
    authEndpoint: ''
    authHeaders: ''
    authPayload: '{"version": "1.0", "clientid": "183SVEgDg5nHbILW//3jvg==", "platform":
      "PC"}'
    authType: NONE
  crawlEndpoints:
  - crawlTasks:
    - action: SAVE_S3
      endpointId: 13
      params: '{}'
      responseMapping: '{"items": "$.items[*]"}'
      stepOrder: 1
      target: RAW_DATA
      type: CRAWLING
    endPointUrl: /products/search
    endpointId: 13
    parameters: categoryNos=791683&order.direction=DESC&pageNumber={}&pageSize={}
  crawlSetting:
    crawlFrequency: 10
    crawlType: API
  headers:
    Accept: '*/*'
    Accept-Encoding: deflate
    Accept-Language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
      Chrome/89.0.4389.82 Safari/537.36
  mappingId: 8
siteType: CRAWL
