baseUrl: https://shop-api.e-ncp.com
countryCode: KR
siteId: 2
siteName: KASINA
siteProfiles:
- crawlAuthSetting:
    authEndpoint: ''
    authHeaders: ''
    authPayload: '{"version": "1.0", "clientid": "183SVEgDg5nHbILW//3jvg==", "platform":
      "PC"}'
    authType: NONE
  crawlEndpoints:
  - crawlTasks:
    - action: SAVE_S3
      endpointId: 84
      params: '{}'
      responseMapping: '{"items": "$.items[*]"}'
      stepOrder: 1
      target: RAW_DATA
      type: CRAWLING
    endPointUrl: /products/search
    endpointId: 84
    parameters: categoryNos=791683&order.direction=DESC&pageNumber={}&pageSize={}
  crawlSetting:
    crawlFrequency: 10
    crawlType: API
  headers:
    Accept: '*/*'
    Accept-Encoding: gzip, deflate
    Accept-Language: en-US,en;q=0.9
    Sec-Ch-Ua-Platform: '"macOS"'
    Sec-Fetch-Site: none
    Sec-Fetch-User: ?1
    Upgrade-Insecure-Requests: '1'
    User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15
      (KHTML, like Gecko) Version/14.0 Safari/605.1.15
  mappingId: 3
siteType: CRAWL
