baseUrl: https://m.web.mustit.co.kr
countryCode: KR
siteId: 1
siteName: MUSTIT
siteProfiles:
- crawlAuthSetting:
    authEndpoint: https://m.web.mustit.co.kr
    authHeaders: Authorization
    authPayload: '"${token_type} ${token}"'
    authType: COOKIE
  crawlEndpoints:
  - crawlTasks:
    - action: SAVE_S3
      endpointId: 2
      params: '{}'
      responseMapping: '{"brands": "$.english.*[*].{''brandNo'': brandNo, ''brandNameEng'':
        brandNameEng, ''brandNameKor'': brandNameKor, ''keyword'': keyword}"}'
      stepOrder: 1
      target: BRAND
      type: CRAWLING
    endPointUrl: /mustit-api/legacy-api/v1/brands
    endpointId: 2
    parameters: ''
  crawlSetting:
    crawlFrequency: 10
    crawlType: API
  headers:
    Accept: '*/*'
    Accept-Encoding: gzip, deflate
    Accept-Language: ko-KR,ko;q=0.9
    Connection: close
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
      (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
  mappingId: 5
- crawlAuthSetting:
    authEndpoint: https://m.web.mustit.co.kr
    authHeaders: Authorization
    authPayload: '"${token_type} ${token}"'
    authType: COOKIE
  crawlEndpoints:
  - crawlTasks:
    - action: SAVE_S3
      endpointId: 3
      params: '{}'
      responseMapping: '{"items": "$.items[*]"}'
      stepOrder: 1
      target: RAW_DATA
      type: CRAWLING
    endPointUrl: /mustit-api/facade-api/v1/search/mini-shop-search
    endpointId: 3
    parameters: sellerId=bino2345&pageNo={}&pageSize={}&order=LATEST
  - crawlTasks:
    - action: SAVE_S3
      endpointId: 4
      params: '{}'
      responseMapping: '{"items": "$.items[*]"}'
      stepOrder: 1
      target: RAW_DATA
      type: CRAWLING
    endPointUrl: /mustit-api/facade-api/v1/search/mini-shop-search
    endpointId: 4
    parameters: sellerId=ccapsule1&pageNo={}&pageSize={}&order=LATEST
  - crawlTasks:
    - action: SAVE_S3
      endpointId: 5
      params: '{}'
      responseMapping: '{"items": "$.items[*]"}'
      stepOrder: 1
      target: RAW_DATA
      type: CRAWLING
    endPointUrl: /mustit-api/facade-api/v1/search/mini-shop-search
    endpointId: 5
    parameters: sellerId=fixedone&pageNo={}&pageSize={}&order=LATEST
  - crawlTasks:
    - action: SAVE_S3
      endpointId: 6
      params: '{}'
      responseMapping: '{"items": "$.items[*]"}'
      stepOrder: 1
      target: RAW_DATA
      type: CRAWLING
    endPointUrl: /mustit-api/facade-api/v1/search/mini-shop-search
    endpointId: 6
    parameters: sellerId=italiagom&pageNo={}&pageSize={}&order=LATEST
  - crawlTasks:
    - action: SAVE_S3
      endpointId: 7
      params: '{}'
      responseMapping: '{"items": "$.items[*]"}'
      stepOrder: 1
      target: RAW_DATA
      type: CRAWLING
    endPointUrl: /mustit-api/facade-api/v1/search/mini-shop-search
    endpointId: 7
    parameters: sellerId=LIKEASTAR&pageNo={}&pageSize={}&order=LATEST
  - crawlTasks:
    - action: SAVE_S3
      endpointId: 8
      params: '{}'
      responseMapping: '{"items": "$.items[*]"}'
      stepOrder: 1
      target: RAW_DATA
      type: CRAWLING
    endPointUrl: /mustit-api/facade-api/v1/search/mini-shop-search
    endpointId: 8
    parameters: sellerId=thefactor2&pageNo={}&pageSize={}&order=LATEST
  - crawlTasks:
    - action: SAVE_S3
      endpointId: 9
      params: '{}'
      responseMapping: '{"items": "$.items[*]"}'
      stepOrder: 1
      target: RAW_DATA
      type: CRAWLING
    endPointUrl: /mustit-api/facade-api/v1/search/mini-shop-search
    endpointId: 9
    parameters: sellerId=viaitalia&pageNo={}&pageSize={}&order=LATEST
  - crawlTasks:
    - action: SAVE_S3
      endpointId: 10
      params: '{}'
      responseMapping: '{"items": "$.items[*]"}'
      stepOrder: 1
      target: RAW_DATA
      type: CRAWLING
    endPointUrl: /mustit-api/facade-api/v1/search/mini-shop-search
    endpointId: 10
    parameters: sellerId=wdrobe&pageNo={}&pageSize={}&order=LATEST
  - crawlTasks:
    - action: SAVE_S3
      endpointId: 11
      params: '{}'
      responseMapping: '{"items": "$.items[*]"}'
      stepOrder: 1
      target: RAW_DATA
      type: CRAWLING
    endPointUrl: /mustit-api/facade-api/v1/search/mini-shop-search
    endpointId: 11
    parameters: sellerId=BONTANO&pageNo={}&pageSize={}&order=LATEST
  - crawlTasks:
    - action: SAVE_S3
      endpointId: 12
      params: '{}'
      responseMapping: '{"items": "$.items[*]"}'
      stepOrder: 1
      target: RAW_DATA
      type: CRAWLING
    endPointUrl: /mustit-api/facade-api/v1/search/mini-shop-search
    endpointId: 12
    parameters: sellerId=bino2345&pageNo={}&pageSize={}&order=LATEST
  crawlSetting:
    crawlFrequency: 10
    crawlType: API
  headers:
    Accept: '*/*'
    Accept-Encoding: gzip, deflate
    Accept-Language: ko-KR,ko;q=0.9
    Connection: close
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
      like Gecko) Chrome/90.0.4430.93 Safari/537.36
  mappingId: 7
siteType: CRAWL
